baseURL = "https://wei-sheng-wang.github.io/"
title = "Wei Sheng's Blog"
theme = "PaperMod"
pagerSize = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Wei Sheng's Blog"
description = "A blog about research, C++, and more"
keywords = ["Blog", "Research", "C++", "Programming"]
author = "Wei Sheng"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
comments = true
ShareButtons = ["linkedin", "reddit", "ycombinator", "x"]

  [params.profileMode]
  enabled = true
  title = "Wei Sheng's Blog"
  subtitle = "Software Engineer | AI Engineer | Trading | C++ Programming Enthusiast"
  imageUrl = "/images/profile.png"
  imageTitle = "my profile"
  imageWidth = 220
  imageHeight = 220

  [[params.profileMode.buttons]]
  name = "Posts"
  url = "posts"

  [[params.profileMode.buttons]]
  name = "Projects"
  url = "projects"



  [[params.profileMode.buttons]]
  name = "About"
  url = "about"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Wei-Sheng-Wang"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/wei-sheng-wang-60b096212/"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:weisheng9822@gmail.com"

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true
style = "monokai"

[menu]
  [[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

  [[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 20

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 30

  [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 40

[outputs]
home = ["HTML", "RSS", "JSON"]
